[versions]

android-plugin = '8.13.0'

android-sdk-compile = '36'
android-sdk-min = '26'
android-sdk-target = '36'

androidx-annotation = '1.9.1'

java-source = '11'

java-toolchain = '21'

kotlin = '2.2.21'


[libraries]

android-library = { module = 'com.android.library:com.android.library.gradle.plugin', version.ref = 'android-plugin' }

androidx-annotation = { module = 'androidx.annotation:annotation', version.ref = 'androidx-annotation' }

bubenheimer-androidutil = { module = 'org.bubenheimer:androidutil', version = '1.0-SNAPSHOT' }

kotlin-gradle-plugin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin' }
